name: QA Tests

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress
        env:
          CYPRESS_reqresApiKey: ${{ secrets.REQRES_API_KEY }}
          CYPRESS_githubToken: ${{ secrets.GITHUB_TOKEN }}
        run: npm test
